# version: '3'

# services:
#   redis-compose:
#     image: redis
#     command: redis-server --requirepass Senha123 --appendonly yes
#     hostname: redis
#     ports:
#       - "6379:6379"
#     volumes:
#       - /home/duducp/Redis:/var/lib/postgresql/data

version: '3'
services:
  redis:
    container_name: redis
    hostname: redis
    image: redis

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    build: .
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - 8081:8081